#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy=1.6.\*
echo -e "\nbackend web-backend\n\tbalance roundrobin\n\tserver web1 35.237.166.41:80 check\n\tserver web2 35.243.221.13:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
