#!/usr/bin/env bash
# Process and PID file.
echo $$ > /var/run/holbertonscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
done
trap 'echo I hate the kill command' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm "/var/run/holbertonscript.pid"; exit' SIGTERM SIGQUIT
