#!/usr/bin/env bash
# Process and PID file.
while true
do
    echo $$ > /var/run/holbertonscript.pid
    echo "To infinity and beyond"
    sleep 2
    trap 'echo I hate the kill command' SIGTERM
    trap 'echo Y U no love me?!' SIGINT
    trap 'rm "/var/run/holbertonscript.pid"; exit' SIGTERM SIGQUIT
done
