#!/usr/bin/env bash
# Manage my process
if [[ $1 == "start" ]]
then
    ./manage_my_process &
    pgrep -fn manage_my_process > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ $1 == "stop" ]]
then
    pkill -F /var/run/my_process.pid
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [[ $1 == "restart" ]]
then
    pkill -F /var/run/my_process.pid
    rm /var/run/my_process.pid
    ./manage_my_process &
    pgrep -fn manage_my_process > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
