#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
file='/etc/passwd'
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done < $file
