#!/usr/bin/env bash
# Nginx is running as the nginx user
kill -9 apache2
chmod 744 /etc/nginx/nginx.conf
sed -i '4i\ user nginx; \n' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
