#!/usr/bin/env bash
# Nginx is running as the nginx user
sudo pkill -o apache2
sudo chmod 744 /etc/nginx/nginx.conf
sudo sed -i "4i\ user nginx; \n'" /etc/nginx/nginx.conf
su nginx -c sed -i "s/8080/80/g" /etc/nginx/sites-available/default
su nginx -c 'service nginx restart'
